public with sharing class GetPlanetsWrapperClass {
	public String name;	//Tatooine
	public String rotation_period;	//23
	public String orbital_period;	//304
	public String diameter;	//10465
	public String climate;	//arid
	public String gravity;	//1 standard
	public String terrain;	//desert
	public String surface_water;	//1
	public String population;	//200000
	public cls_residents[] residents;
	public cls_films[] films;
	public String url;	//https://swapi.dev/api/planets/1/
	class cls_residents {
		public String 0;	//h
		public String 1;	//t
		public String 2;	//t
		public String 3;	//p
		public String 4;	//s
		public String 5;	//:
		public String 6;	///
		public String 7;	///
		public String 8;	//s
		public String 9;	//w
		public String 10;	//a
		public String 11;	//p
		public String 12;	//i
		public String 13;	//.
		public String 14;	//d
		public String 15;	//e
		public String 16;	//v
		public String 17;	///
		public String 18;	//a
		public String 19;	//p
		public String 20;	//i
		public String 21;	///
		public String 22;	//p
		public String 23;	//e
		public String 24;	//o
		public String 25;	//p
		public String 26;	//l
		public String 27;	//e
		public String 28;	///
		public String 29;	//1
		public String 30;	///
	}
	class cls_films {
		public String 0;	//h
		public String 1;	//t
		public String 2;	//t
		public String 3;	//p
		public String 4;	//s
		public String 5;	//:
		public String 6;	///
		public String 7;	///
		public String 8;	//s
		public String 9;	//w
		public String 10;	//a
		public String 11;	//p
		public String 12;	//i
		public String 13;	//.
		public String 14;	//d
		public String 15;	//e
		public String 16;	//v
		public String 17;	///
		public String 18;	//a
		public String 19;	//p
		public String 20;	//i
		public String 21;	///
		public String 22;	//f
		public String 23;	//i
		public String 24;	//l
		public String 25;	//m
		public String 26;	//s
		public String 27;	///
		public String 28;	//1
		public String 29;	///
	}
}
